# Configuration for .github/workflows/pull_request_label.yml.

'type-infra':
  - changed-files:
      - any-glob-to-any-file: '.github/**'

'package:benchmark_harness':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/benchmark_harness/**'

'package:boolean_selector':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/boolean_selector/**'

'package:cli_config':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/cli_config/**'

'package:coverage':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/coverage/**'

'package:extension_discovery':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/extension_discovery/**'

'package:file':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/file/**'

'package:file_testing':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/file_testing/**'

'package:graphs':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/graphs/**'

'package:mime':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/mime/**'

'package:oauth2':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/oauth2/**'

'package:source_map_stack_trace':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/source_map_stack_trace/**'

'package:unified_analytics':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/unified_analytics/**'
