name: file
author: Matan Lurey <matanl@google.com>
description: A pluggable file system abstraction for Dart.
homepage: https://github.com/matanlurey/file
version: 0.1.0
dependencies:
dev_dependencies:
  test: any
